import type { MaintenanceLogUi } from "@/app/maintenance/_types/maintenance-ui";

/** Mock rows for boneyard-js CLI capture of `maintenance-list`. */
export const MAINTENANCE_LIST_FIXTURE_LOGS: MaintenanceLogUi[] = [
  {
    id: 101,
    vehicleId: "veh-fixture-1",
    vehicleNameModel: "Force Traveller 3350",
    vehicleRegistration: "MH12AB1234",
    vehicleStatus: "in_shop",
    maintenanceTypeId: "type-service",
    maintenanceTypeCode: "SERVICE",
    maintenanceTypeName: "Periodic service",
    vendorName: "City Motors",
    description: "Oil change and filters",
    costInr: "4500",
    startedAt: "2026-07-01T10:00:00.000Z",
    completedAt: null,
    status: "open",
    odometerAtServiceKm: "45200",
    nextDueOdometerKm: "50200",
  },
  {
    id: 102,
    vehicleId: "veh-fixture-2",
    vehicleNameModel: "Tata Winger",
    vehicleRegistration: "MH14CD5678",
    vehicleStatus: "available",
    maintenanceTypeId: "type-tires",
    maintenanceTypeCode: "TIRES",
    maintenanceTypeName: "Tire replacement",
    vendorName: "Highway Tyres",
    description: "Front pair replaced",
    costInr: "12800",
    startedAt: "2026-06-20T09:15:00.000Z",
    completedAt: "2026-06-20T14:30:00.000Z",
    status: "closed",
    odometerAtServiceKm: "38100",
    nextDueOdometerKm: null,
  },
  {
    id: 103,
    vehicleId: "veh-fixture-3",
    vehicleNameModel: "Mahindra Bolero",
    vehicleRegistration: "MH12EF9012",
    vehicleStatus: "available",
    maintenanceTypeId: "type-brake",
    maintenanceTypeCode: "BRAKES",
    maintenanceTypeName: "Brake service",
    vendorName: "SafeStop Garage",
    description: "Pads and fluid",
    costInr: "6200",
    startedAt: "2026-06-10T11:00:00.000Z",
    completedAt: "2026-06-10T16:45:00.000Z",
    status: "closed",
    odometerAtServiceKm: "52150",
    nextDueOdometerKm: "57150",
  },
  {
    id: 104,
    vehicleId: "veh-fixture-4",
    vehicleNameModel: "Ashok Leyland Dost",
    vehicleRegistration: "MH15GH3456",
    vehicleStatus: "in_shop",
    maintenanceTypeId: "type-other",
    maintenanceTypeCode: "OTHER",
    maintenanceTypeName: "Other",
    vendorName: "Fleet Care",
    description: "AC compressor repair",
    costInr: "9800",
    startedAt: "2026-07-05T08:30:00.000Z",
    completedAt: null,
    status: "open",
    odometerAtServiceKm: "29400",
    nextDueOdometerKm: null,
  },
];
