import type { DriverUi } from "@/app/drivers/_types/drivers-ui";

export const FIXTURE_DRIVERS = [
  {
    id: "fixture-driver-1",
    fullName: "Amina Okello",
    licenseNumber: "UG-DL-100001",
    licenseCategoryId: "fixture-cat-1",
    licenseCategoryCode: "B",
    licenseCategoryName: "Light Vehicle",
    licenseExpiryDate: "2027-06-15",
    contactNumber: "+256700000001",
    safetyScore: 98,
    status: "available",
    notes: null,
    assignedTripCount: 12,
    completedTripCount: 11,
    tripCompletionPct: 92,
    isLicenseExpired: false,
    isLicenseExpiringSoon: false,
  },
  {
    id: "fixture-driver-2",
    fullName: "James Mutebi",
    licenseNumber: "UG-DL-100002",
    licenseCategoryId: "fixture-cat-2",
    licenseCategoryCode: "C",
    licenseCategoryName: "Heavy Goods",
    licenseExpiryDate: "2026-08-01",
    contactNumber: "+256700000002",
    safetyScore: 91,
    status: "on_trip",
    notes: null,
    assignedTripCount: 20,
    completedTripCount: 18,
    tripCompletionPct: 90,
    isLicenseExpired: false,
    isLicenseExpiringSoon: true,
  },
  {
    id: "fixture-driver-3",
    fullName: "Sarah Namukasa",
    licenseNumber: "UG-DL-100003",
    licenseCategoryId: "fixture-cat-1",
    licenseCategoryCode: "B",
    licenseCategoryName: "Light Vehicle",
    licenseExpiryDate: "2025-01-10",
    contactNumber: "+256700000003",
    safetyScore: 85,
    status: "off_duty",
    notes: null,
    assignedTripCount: 8,
    completedTripCount: 8,
    tripCompletionPct: 100,
    isLicenseExpired: true,
    isLicenseExpiringSoon: false,
  },
  {
    id: "fixture-driver-4",
    fullName: "Peter Ssemwogerere",
    licenseNumber: "UG-DL-100004",
    licenseCategoryId: "fixture-cat-2",
    licenseCategoryCode: "C",
    licenseCategoryName: "Heavy Goods",
    licenseExpiryDate: "2028-03-22",
    contactNumber: "+256700000004",
    safetyScore: 76,
    status: "suspended",
    notes: "Pending review",
    assignedTripCount: 5,
    completedTripCount: 3,
    tripCompletionPct: 60,
    isLicenseExpired: false,
    isLicenseExpiringSoon: false,
  },
] as const satisfies readonly DriverUi[];
