import type { TripRow } from "@/app/dashboard/_types/trip";

export const demoTrips: TripRow[] = [
  {
    id: "TRP-1042",
    route: "Gandhinagar Depot → Ahmedabad Hub",
    vehicle: "Van-05",
    driver: "Alex Kumar",
    cargoKg: 450,
    status: "dispatched",
    distanceKm: 28,
  },
  {
    id: "TRP-1041",
    route: "Surat Warehouse → Vadodara DC",
    vehicle: "Truck-12",
    driver: "Ravi Patel",
    cargoKg: 2800,
    status: "completed",
    distanceKm: 164,
  },
  {
    id: "TRP-1040",
    route: "Rajkot Plant → Bhavnagar Port",
    vehicle: "Truck-08",
    driver: "Suresh Mehta",
    cargoKg: 4200,
    status: "completed",
    distanceKm: 198,
  },
  {
    id: "TRP-1039",
    route: "Ahmedabad Hub → Gandhinagar Depot",
    vehicle: "Van-03",
    driver: "Priya Shah",
    cargoKg: 320,
    status: "draft",
    distanceKm: 28,
  },
  {
    id: "TRP-1038",
    route: "Anand Cold Storage → Ahmedabad Hub",
    vehicle: "Reefer-02",
    driver: "Vikram Joshi",
    cargoKg: 1800,
    status: "dispatched",
    distanceKm: 74,
  },
  {
    id: "TRP-1037",
    route: "Mehsana Factory → Surat Warehouse",
    vehicle: "Truck-15",
    driver: "Amit Desai",
    cargoKg: 3500,
    status: "completed",
    distanceKm: 312,
  },
];
