/**
 * Sample trips aligned with `src/app/dashboard/_lib/demo-trips.ts` and fleet seeds.
 * Completed trips also seed fuel + expense + revenue logs (ADR-056).
 */

import type { SeedTripRow } from "./_types/seed-trips";

export const TRIP_SEEDS: readonly SeedTripRow[] = [
  {
    seedKey: "TRP-1042",
    sourceLocationCode: "GND_DEPOT",
    destinationLocationCode: "AHM_HUB",
    vehicleNameModel: "Van-05",
    driverFullName: "Alex Kumar",
    cargoWeightKg: "450.00",
    plannedDistanceKm: "28.00",
    status: "dispatched",
    startOdometerKm: "45230.0",
    dispatchedOn: "2026-07-10",
  },
  {
    seedKey: "TRP-1041",
    sourceLocationCode: "SUR_WH",
    destinationLocationCode: "VAD_DC",
    vehicleNameModel: "Truck-12",
    driverFullName: "Ravi Patel",
    cargoWeightKg: "2800.00",
    plannedDistanceKm: "164.00",
    status: "completed",
    startOdometerKm: "128286.0",
    endOdometerKm: "128450.0",
    actualDistanceKm: "164.00",
    fuelConsumedLiters: "48.500",
    fuelCostInr: "4350.00",
    completedOn: "2026-05-18",
    dispatchedOn: "2026-05-17",
    expenseAmountInr: "420.00",
    expenseCategoryCode: "TOLL",
  },
  {
    seedKey: "TRP-1040",
    sourceLocationCode: "RJT_PLANT",
    destinationLocationCode: "BHV_PORT",
    vehicleNameModel: "Truck-08",
    driverFullName: "Suresh Mehta",
    cargoWeightKg: "4200.00",
    plannedDistanceKm: "198.00",
    status: "completed",
    startOdometerKm: "201002.0",
    endOdometerKm: "201200.0",
    actualDistanceKm: "198.00",
    fuelConsumedLiters: "72.000",
    fuelCostInr: "6480.00",
    completedOn: "2026-06-04",
    dispatchedOn: "2026-06-03",
    expenseAmountInr: "550.00",
    expenseCategoryCode: "TOLL",
  },
  {
    seedKey: "TRP-1039",
    sourceLocationCode: "AHM_HUB",
    destinationLocationCode: "GND_DEPOT",
    vehicleNameModel: "Van-03",
    driverFullName: "Priya Shah",
    cargoWeightKg: "320.00",
    plannedDistanceKm: "28.00",
    status: "draft",
  },
  {
    seedKey: "TRP-1038",
    sourceLocationCode: "ANAND_CS",
    destinationLocationCode: "AHM_HUB",
    vehicleNameModel: "Reefer-02",
    driverFullName: "Vikram Joshi",
    cargoWeightKg: "1800.00",
    plannedDistanceKm: "74.00",
    status: "dispatched",
    startOdometerKm: "96410.0",
    dispatchedOn: "2026-07-09",
  },
  {
    seedKey: "TRP-1037",
    sourceLocationCode: "MHS_FACTORY",
    destinationLocationCode: "SUR_WH",
    vehicleNameModel: "Truck-15",
    driverFullName: "Amit Desai",
    cargoWeightKg: "3500.00",
    plannedDistanceKm: "312.00",
    status: "completed",
    startOdometerKm: "156468.0",
    endOdometerKm: "156780.0",
    actualDistanceKm: "312.00",
    fuelConsumedLiters: "95.200",
    fuelCostInr: "8568.00",
    completedOn: "2026-07-02",
    dispatchedOn: "2026-07-01",
    expenseAmountInr: "890.00",
    expenseCategoryCode: "MISC",
  },
] as const;
