"use client";
// Auto-generated by scripts/boneyard-build.ts — do not edit by hand
import { registerBones } from "boneyard-js";
import { configureBoneyard } from "boneyard-js/react";

import { polishTableBones } from "@/lib/boneyard/polish-table-bones";
import { BONEYARD_RUNTIME } from "@/lib/boneyard/runtime-style";

import _analytics_report from "@/bones/analytics-report.bones.json";
import _dashboard_recent_trips from "@/bones/dashboard-recent-trips.bones.json";
import _documents_table from "@/bones/documents-table.bones.json";
import _drivers_list from "@/bones/drivers-list.bones.json";
import _fuel_expenses_content from "@/bones/fuel-expenses-content.bones.json";
import _maintenance_list from "@/bones/maintenance-list.bones.json";
import _trips_live_board from "@/bones/trips-live-board.bones.json";
import _vehicles_table from "@/bones/vehicles-table.bones.json";

// Boneyard shimmer only (never CSS animate-pulse). Colors track theme muted.
configureBoneyard({
  animate: BONEYARD_RUNTIME.animate,
  color: BONEYARD_RUNTIME.color,
  darkColor: BONEYARD_RUNTIME.darkColor,
  darkShimmerColor: BONEYARD_RUNTIME.darkShimmerColor,
  select: BONEYARD_RUNTIME.select,
  shimmerAngle: BONEYARD_RUNTIME.shimmerAngle,
  shimmerColor: BONEYARD_RUNTIME.shimmerColor,
  speed: BONEYARD_RUNTIME.speed,
  transition: BONEYARD_RUNTIME.transition,
});

const TABLE_SKELETONS = new Set([
  "dashboard-recent-trips",
  "documents-table",
  "drivers-list",
  "fuel-expenses-content",
  "maintenance-list",
  "vehicles-table",
]);

function maybePolish<T>(name: string, data: T): T {
  return TABLE_SKELETONS.has(name) ? polishTableBones(data) : data;
}

registerBones({
  "analytics-report": maybePolish("analytics-report", _analytics_report),
  "dashboard-recent-trips": maybePolish("dashboard-recent-trips", _dashboard_recent_trips),
  "documents-table": maybePolish("documents-table", _documents_table),
  "drivers-list": maybePolish("drivers-list", _drivers_list),
  "fuel-expenses-content": maybePolish("fuel-expenses-content", _fuel_expenses_content),
  "maintenance-list": maybePolish("maintenance-list", _maintenance_list),
  "trips-live-board": maybePolish("trips-live-board", _trips_live_board),
  "vehicles-table": maybePolish("vehicles-table", _vehicles_table),
});
